### ISSUE TITLE
Why not collaborate?

### ISSUE THREAD

**Issue by 130s** [MahsaP/gazebo_ros_denso#1]
Hi I just found this repo (linked from [answers.ros](http://answers.ros.org/question/214801/using-ikfast-for-denso/?answer=216244#post-id-216244)) and noticed that the model files in your repository are identical to those in [our repo](https://github.com/start-jsk/denso/tree/46adc3ffadbcba8d9eaf4744621d217a69ee9989/vs060/model/meshes); (we worked with the manufacturer, Densowave, and obtained models from them). I don't know if you copied from there but since our package is licensed under BSD copying for your purpose is legitimate :).

Anyways, since it looks like we're working on the same robot why don't we use a single repository, instead of duplicating the code? That way you could get more testers, reviewers, and maybe even more features in the future (e.g. we just merged Gazebo feature https://github.com/start-jsk/denso/pull/52). Currently we don't really have an active project regarding this robot but we're always watching over the repository and responsive enough for the inquiries. Again this is just a suggestion. Thanks!

**Comment by MahsaP** [comment]
Hi, 
Yes, I have used your package (mesh files and the URDF file) and modified it for my project. I have to edit my files to address that your package has been used. Sorry.
I agree with you.It would be a great idea to do that. You know, I have worked on this robot for several months. Have you seen my code? I have attached a camera on the robot flange for visual servoing. Please give me details how to share codes on a single repository.
Thank you.

**Comment by 130s** [comment]
You're most welcomed to use our opensource code, no need to be sorry :)

If I were you, I would fork [start-jsk/denso](https://github.com/start-jsk/denso) repository, add some codes that can be commonly used for every body and make a pull request for that. Then also add the code that is specific to your work. 

Looking at your code and actually ran some launch files, I would:
- merge denso_control and denso_gazebo, maybe into `vs060_gazebo` package
  - Since most of the functionality in these 2 packages seem to be Gazebo specific and have nothing to do with the controller defined in the packages in the denso repository (denso package currently doesn't depend on ros_control framework for a historical reason. That said in its current form it might not be very Gazebo friendly because ros_control is suited for Gazebo).
  - I renamed `denso_*` to `vs060_*` since the data you copied from is for Denso's vs060 robot.
- leave the content of `denso_description` as it is
  - since its content seems specific to your work. But still I would remove model files or whatever identical to those stored in `vs060` package
  - Maybe you can rename the package name. It's a bit too generic.

Result would look like this:

(in your forked `start-jsk/denso` repository)

```
$ tree -L 1
.
├── denso
├── denso_controller
├── denso_irex_ui
├── denso_description (or you may name it better)
├── denso_launch
├── denso_pendant_publisher
├── vs060
├── vs060A1_AV6_NNN_NNN_arm_navigation
└── vs060_gazebo
└── vs060_moveit_config
```

Drawback is if you've already written some application code somewhere else that uses your current setting, you may have to change the package names.

I'll open a pull request against your repository that partly implements the idea above. But this is your work, so no push ;). I just want you to take advantage of the power of opensource development, and also want some collaborators using the same robot. Thanks a lot!

**Comment by 130s** [comment]
See https://github.com/MahsaP/gazebo_ros_denso/issues/2 that partially implements the idea i mentioned above.

**Comment by MahsaP** [comment]
Thank you for your suggestion. I have modified my package. Also, I made https://github.com/start-jsk/denso/pull/53 pull request. For this request I have removed the camera and made it in a way that other people can compile it with other vs060 packages.

**Comment by 130s** [comment]
@MahsaP Thanks for putting the PR together! Apologies reviewing it is taking time, but I hope you can keep doing on your own work without problems.
